# Generated by Django 2.1.7 on 2019-04-01 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('roll_number', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('section', models.CharField(blank=True, max_length=5, null=True)),
                ('branch', models.CharField(blank=True, max_length=5, null=True)),
                ('batch', models.CharField(blank=True, max_length=4, null=True)),
            ],
            options={
                'db_table': 'student',
                'managed': False,
            },
        ),
    ]
